### ISSUE TITLE
colloc_adapt Argument Not Passed to train_PIKAN Function

### ISSUE THREAD

**Issue by vsingh10** [srigas/jaxKAN#1]
It appears that the colloc_adapt dictionary, which is used for adaptive collocation point resampling, is referenced within the train_PIKAN function, but it has not been explicitly included as an argument in the function definition.

Because of that getting the following error as shown in the image attached.
![Screenshot 2024-10-07 162202](https://github.com/user-attachments/assets/4b53d7b8-b0ac-4d8b-a752-0f9d1bcd7f55)

**Comment by srigas** [comment]
Nice catch @vsingh10 ! It has been fixed in the new release :)
